[![Coverage Status](https://coveralls.io/repos/github/Irutingabo/cickodes/badge.svg?branch=ch-setup-working-env-171619095)](https://coveralls.io/github/Irutingabo/cickodes?branch=ch-setup-working-env-171619095)
